// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a human-readable explanation of why a piece of content might be misleading.
 *
 * - generateMisinformationExplanation - A function that generates the explanation.
 * - GenerateMisinformationExplanationInput - The input type for the generateMisinformationExplanation function.
 * - GenerateMisinformationExplanationOutput - The return type for the generateMisinformationExplanation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMisinformationExplanationInputSchema = z.object({
  content: z.string().describe('The content to analyze for potential misinformation.'),
  indicators: z.array(z.string()).describe('A list of indicators that suggest the content may be misleading.'),
});
export type GenerateMisinformationExplanationInput = z.infer<typeof GenerateMisinformationExplanationInputSchema>;

const GenerateMisinformationExplanationOutputSchema = z.object({
  explanation: z.string().describe('A human-readable explanation of why the content might be misleading.'),
});
export type GenerateMisinformationExplanationOutput = z.infer<typeof GenerateMisinformationExplanationOutputSchema>;

export async function generateMisinformationExplanation(input: GenerateMisinformationExplanationInput): Promise<GenerateMisinformationExplanationOutput> {
  return generateMisinformationExplanationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMisinformationExplanationPrompt',
  input: {schema: GenerateMisinformationExplanationInputSchema},
  output: {schema: GenerateMisinformationExplanationOutputSchema},
  prompt: `You are an expert in identifying misinformation. Given the following content and a list of indicators that suggest it may be misleading, generate a human-readable explanation of why the content might be misleading.

Content: {{{content}}}

Indicators: {{#each indicators}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

Explanation:`,
});

const generateMisinformationExplanationFlow = ai.defineFlow(
  {
    name: 'generateMisinformationExplanationFlow',
    inputSchema: GenerateMisinformationExplanationInputSchema,
    outputSchema: GenerateMisinformationExplanationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
